name: Daily trigger

on:
  schedule:
    - cron: '0 16 * * *'
    - cron: '5 16 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: curl -s https://am24logbujoqctvut7bqmk.streamlit.app/// > /dev/null
